function tests = testCoolingCore
%TESTCOOLINGCORE Verification tests for the synthetic cooling lesson core.
% All inputs and outputs use SI units unless the field name states otherwise.
tests = functiontests(localfunctions);
end

function testSteadyStateConservesLiquidHeat(testCase)
input = struct( ...
    'itLoad_W', 10000, ...
    'liquidCaptureFraction', 0.8, ...
    'coolantMassFlow_kg_s', 0.20, ...
    'coolantSpecificHeat_J_kgK', 4180, ...
    'supplyTemperature_C', 25);

state = calculateCoolingState(input);

verifyEqual(testCase, state.liquidHeat_W, 8000, 'AbsTol', 1e-12);
verifyEqual(testCase, state.airHeat_W, 2000, 'AbsTol', 1e-12);
verifyEqual(testCase, state.coolantDeltaT_K, 8000 / (0.20 * 4180), 'AbsTol', 1e-12);
verifyEqual(testCase, state.returnTemperature_C, ...
    25 + 8000 / (0.20 * 4180), 'AbsTol', 1e-12);
verifyEqual(testCase, state.energyResidual_W, 0, 'AbsTol', 1e-9);
end

function testHigherFlowReducesCoolantTemperatureRise(testCase)
base = struct( ...
    'itLoad_W', 50000, ...
    'liquidCaptureFraction', 1.0, ...
    'coolantMassFlow_kg_s', 0.25, ...
    'coolantSpecificHeat_J_kgK', 4180, ...
    'supplyTemperature_C', 25);
lowFlow = calculateCoolingState(base);
base.coolantMassFlow_kg_s = 0.50;
highFlow = calculateCoolingState(base);

verifyLessThan(testCase, highFlow.coolantDeltaT_K, lowFlow.coolantDeltaT_K);
verifyEqual(testCase, highFlow.coolantDeltaT_K, lowFlow.coolantDeltaT_K / 2, ...
    'AbsTol', 1e-12);
end

function testNoLiquidCaptureLeavesCoolantUnchanged(testCase)
input = struct( ...
    'itLoad_W', 12000, ...
    'liquidCaptureFraction', 0, ...
    'coolantMassFlow_kg_s', 0.10, ...
    'coolantSpecificHeat_J_kgK', 4180, ...
    'supplyTemperature_C', 30);

state = calculateCoolingState(input);

verifyEqual(testCase, state.liquidHeat_W, 0, 'AbsTol', 1e-12);
verifyEqual(testCase, state.returnTemperature_C, 30, 'AbsTol', 1e-12);
verifyEqual(testCase, state.airHeat_W, 12000, 'AbsTol', 1e-12);
end

function testInvalidInputsAreRejected(testCase)
input = struct( ...
    'itLoad_W', 1000, ...
    'liquidCaptureFraction', 1.1, ...
    'coolantMassFlow_kg_s', 0.10, ...
    'coolantSpecificHeat_J_kgK', 4180, ...
    'supplyTemperature_C', 25);

verifyError(testCase, @() calculateCoolingState(input), ...
    'DataCenterCooling:InvalidLiquidCaptureFraction');
end

function testTransientConservesEnergyAtEachTimeStep(testCase)
parameters = struct( ...
    'liquidCaptureFraction', 0.8, ...
    'coolantMassFlow_kg_s', 0.20, ...
    'coolantSpecificHeat_J_kgK', 4180, ...
    'supplyTemperature_C', 25, ...
    'thermalResistance_K_W', 0.003, ...
    'thermalCapacitance_J_K', 30000, ...
    'initialComponentTemperature_C', 25);
time_s = linspace(0, 120, 121)';
itLoad_W = 5000 + 5000 .* (time_s >= 30);

simulation = simulateComponentTransient(parameters, time_s, itLoad_W);

verifyLessThan(testCase, max(abs(simulation.energyResidual_W)), 1e-7);
verifyGreaterThan(testCase, simulation.componentTemperature_C(end), ...
    simulation.componentTemperature_C(1));
verifyGreaterThan(testCase, simulation.returnTemperature_C(end), ...
    parameters.supplyTemperature_C);
end

function testTransientApproachesExpectedSteadyTemperature(testCase)
parameters = struct( ...
    'liquidCaptureFraction', 1.0, ...
    'coolantMassFlow_kg_s', 0.20, ...
    'coolantSpecificHeat_J_kgK', 4180, ...
    'supplyTemperature_C', 25, ...
    'thermalResistance_K_W', 0.002, ...
    'thermalCapacitance_J_K', 10000, ...
    'initialComponentTemperature_C', 25);
time_s = linspace(0, 200, 1001)';
itLoad_W = 5000 * ones(size(time_s));

simulation = simulateComponentTransient(parameters, time_s, itLoad_W);

expectedSteady_C = 25 + 5000 * 0.002;
verifyEqual(testCase, simulation.componentTemperature_C(end), expectedSteady_C, ...
    'AbsTol', 0.01);
end

function testExplorerLaunchesAndRefreshesAHiddenFigure(testCase)
projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(projectRoot);
app = DataCenterCoolingExplorer('Visible', 'off');
cleanup = onCleanup(@() deleteIfValid(app.Figure)); %#ok<NASGU>

verifyTrue(testCase, isvalid(app.Figure));
verifyTrue(testCase, contains(app.Labels.returnTemperature.Text, 'Liquid-loop return'));

initialRise = app.Labels.coolantRise.Text;
app.Controls.coolantFlow.Value = 0.40;
app.Refresh();
verifyTrue(testCase, contains(app.Labels.coolantRise.Text, 'Coolant temperature rise'));
verifyNotEqual(testCase, app.Labels.coolantRise.Text, initialRise);
end

function deleteIfValid(graphicObject)
if isvalid(graphicObject)
    delete(graphicObject);
end
end
