function preset = getExplorerPreset(presetName)
%GETEXPLORERPRESET Return a reproducible synthetic teaching scenario.
%
%   names  = getExplorerPreset()      returns the scenario names in lesson order.
%   preset = getExplorerPreset(name)  returns one scenario.
%
% Each preset is illustrative. Values are declared assumptions, not measured
% data or design recommendations for a specific rack or cooling system.
%
% Every scenario except the baseline changes the baseline in a deliberate way
% and carries a prediction question. The Explorer asks for the prediction
% before it loads the scenario, then computes the observed change from the
% model. The expectedChange field records the answer so that the automated
% tests can confirm the lesson text agrees with the physics.

names = {'Moderate liquid cooling', 'Flow-limited loop', ...
    'Lower thermal resistance', 'High-density stress test'};
if nargin == 0
    preset = names;
    return
end

baseline = makePreset('Moderate liquid cooling', 10, 0.80, 0.20, 25, 1.50, ...
    ['Baseline case. Read the coolant temperature rise and the steady component ', ...
     'temperature, then choose another scenario. Each one asks for a prediction ', ...
     'before the sliders move.'], []);
degC = [char(176) 'C'];

name = string(presetName);
switch name
    case "Moderate liquid cooling"
        preset = baseline;
    case "Flow-limited loop"
        flow_kg_s = 0.08;
        preset = makePreset(name, baseline.itLoad_kW, baseline.liquidCaptureFraction, ...
            flow_kg_s, baseline.supplyTemperature_C, baseline.thermalResistance_K_kW, ...
            ['Same load, heat split, and resistance as the baseline, with lower flow. ', ...
             'Compare the coolant rise and the component temperature with the baseline.'], ...
            makePrediction( ...
                sprintf(['Coolant flow drops from %.2f to %.2f kg/s. Load, heat split, ', ...
                    'and resistance match the baseline. How will the steady component ', ...
                    'temperature change?'], baseline.coolantMassFlow_kg_s, flow_kg_s), ...
                'componentTemperature_C', 'steady component temperature', 1, degC, 'rise', ...
                ['Lower flow means a smaller capacity rate (mass flow times specific heat), ', ...
                 'so the coolant warms more as it passes the component. The component must ', ...
                 'run hotter to push the same heat into warmer coolant. The declared heat ', ...
                 'split does not change.']));
    case "Lower thermal resistance"
        resistance_K_kW = 0.75;
        preset = makePreset(name, baseline.itLoad_kW, baseline.liquidCaptureFraction, ...
            baseline.coolantMassFlow_kg_s, baseline.supplyTemperature_C, resistance_K_kW, ...
            ['Same load, heat split, and flow as the baseline, with half the ', ...
             'component-to-coolant resistance. Compare which outputs moved and which did not.'], ...
            makePrediction( ...
                sprintf(['The component-to-coolant resistance is halved, from %.2f to ', ...
                    '%.2f K/kW. Load, heat split, and flow match the baseline. How will ', ...
                    'the liquid-loop return temperature change?'], ...
                    baseline.thermalResistance_K_kW, resistance_K_kW), ...
                'returnTemperature_C', 'liquid-loop return temperature', 1, degC, 'same', ...
                ['The energy balance Q_liquid = m_dot c_p (T_return - T_supply) fixes the ', ...
                 'return temperature. A better thermal path lowers the component temperature, ', ...
                 'but the coolant still carries the same heat at the same flow.']));
    case "High-density stress test"
        load_kW = 40;
        capture = 0.90;
        preset = makePreset(name, load_kW, capture, 0.25, baseline.supplyTemperature_C, 2.00, ...
            ['A deliberately demanding case. Check where the one-node component estimate ', ...
             'lands and decide which assumption you would question first.'], ...
            makePrediction( ...
                sprintf(['IT load rises from %.0f to %.0f kW, and liquid capture rises from ', ...
                    '%.0f%% to %.0f%%. How will the heat left for the room-air path change?'], ...
                    baseline.itLoad_kW, load_kW, 100 * baseline.liquidCaptureFraction, ...
                    100 * capture), ...
                'airHeat_W', 'room-air heat', 1e-3, 'kW', 'rise', ...
                ['The air path carries (1 - f_liquid) Q_IT. A larger capture fraction of a much ', ...
                 'larger load can still leave more heat for room air, so a capture fraction and ', ...
                 'an absolute heat rate answer different design questions.']));
    otherwise
        error('DataCenterCooling:UnknownPreset', ...
            'Unknown preset "%s". Choose a named Explorer teaching scenario.', name);
end
end

function preset = makePreset(name, itLoad_kW, liquidCaptureFraction, ...
        coolantMassFlow_kg_s, supplyTemperature_C, thermalResistance_K_kW, learningGoal, prediction)
preset = struct( ...
    'name', char(name), ...
    'itLoad_kW', itLoad_kW, ...
    'liquidCaptureFraction', liquidCaptureFraction, ...
    'coolantMassFlow_kg_s', coolantMassFlow_kg_s, ...
    'supplyTemperature_C', supplyTemperature_C, ...
    'thermalResistance_K_kW', thermalResistance_K_kW, ...
    'learningGoal', learningGoal);
preset.prediction = prediction;
end

function prediction = makePrediction(prompt, quantity, quantityLabel, displayScale, ...
        displayUnit, expectedChange, explanation)
prediction = struct( ...
    'baseline', 'Moderate liquid cooling', ...
    'prompt', prompt, ...
    'quantity', quantity, ...
    'quantityLabel', quantityLabel, ...
    'displayScale', displayScale, ...
    'displayUnit', displayUnit, ...
    'expectedChange', expectedChange, ...
    'explanation', explanation);
end
