function preset = getExplorerPreset(presetName)
%GETEXPLORERPRESET Return a reproducible synthetic teaching scenario.
%
% Each preset is illustrative. Values are declared assumptions, not measured
% data or design recommendations for a specific rack or cooling system.

name = string(presetName);
switch name
    case "Moderate liquid cooling"
        preset = makePreset( ...
            name, 10, 0.80, 0.20, 25, 1.5, ...
            'Predict how an 80% liquid heat partition sets coolant temperature rise.');
    case "Flow-limited loop"
        preset = makePreset( ...
            name, 20, 0.80, 0.08, 25, 1.5, ...
            'Compare this case with moderate cooling: the heat split is unchanged, but lower flow raises coolant temperature rise.');
    case "High-density stress test"
        preset = makePreset( ...
            name, 40, 0.90, 0.25, 25, 2.0, ...
            'Identify when a simple one-node calculation signals that assumed thermal resistance and flow require scrutiny.');
    otherwise
        error('DataCenterCooling:UnknownPreset', ...
            'Unknown preset "%s". Choose a named Explorer teaching scenario.', name);
end
end

function preset = makePreset(name, itLoad_kW, liquidCaptureFraction, ...
        coolantMassFlow_kg_s, supplyTemperature_C, thermalResistance_K_kW, learningGoal)
preset = struct( ...
    'name', char(name), ...
    'itLoad_kW', itLoad_kW, ...
    'liquidCaptureFraction', liquidCaptureFraction, ...
    'coolantMassFlow_kg_s', coolantMassFlow_kg_s, ...
    'supplyTemperature_C', supplyTemperature_C, ...
    'thermalResistance_K_kW', thermalResistance_K_kW, ...
    'learningGoal', learningGoal);
end
