function simulation = simulateComponentTransient(parameters, time_s, itLoad_W)
%SIMULATECOMPONENTTRANSIENT Solve a one-node component-to-liquid model.
%
% Governing equations:
%   C_th*dT_component/dt = Q_liquid - Q_to_coolant
%   Q_to_coolant = (T_component - T_supply)/R_eff
%   T_return = T_supply + Q_to_coolant/(m_dot*c_p)
%
% R_eff is the effective component-to-supply resistance from
% calculateWallCoupling, so the return temperature never exceeds the
% component temperature. The coolant is treated as quasi-steady (its own heat
% capacity is neglected) and enters at a fixed supply temperature.
%
% The IT load is held constant between samples (zero-order hold): the value
% at time_s(k) applies on [time_s(k), time_s(k+1)). For that input the
% first-order equation has the exact solution
%   T(k+1) = T_ss(k) + (T(k) - T_ss(k))*exp(-(t(k+1) - t(k))/tau),
% with tau = R_eff*C_th and T_ss(k) = T_supply + Q_liquid(k)*R_eff, which this
% function evaluates directly. It does not resolve cold-plate geometry,
% pressure drop, spatial hotspots, or controls.

validateTransientInputs(parameters, time_s, itLoad_W);

time_s = time_s(:);
itLoad_W = itLoad_W(:);
liquidLoad_W = parameters.liquidCaptureFraction .* itLoad_W;

coupling = calculateWallCoupling(parameters.coolantMassFlow_kg_s, ...
    parameters.coolantSpecificHeat_J_kgK, parameters.thermalResistance_K_W);
effectiveResistance_K_W = coupling.effectiveResistance_K_W;
timeConstant_s = effectiveResistance_K_W * parameters.thermalCapacitance_J_K;

steadyTemperature_C = parameters.supplyTemperature_C + liquidLoad_W .* effectiveResistance_K_W;
decay = exp(-diff(time_s) ./ timeConstant_s);
componentTemperature_C = zeros(size(time_s));
componentTemperature_C(1) = parameters.initialComponentTemperature_C;
for index = 1:numel(time_s) - 1
    componentTemperature_C(index + 1) = steadyTemperature_C(index) + ...
        (componentTemperature_C(index) - steadyTemperature_C(index)) * decay(index);
end

heatToCoolant_W = (componentTemperature_C - parameters.supplyTemperature_C) ./ ...
    effectiveResistance_K_W;
returnTemperature_C = parameters.supplyTemperature_C + heatToCoolant_W ./ ...
    coupling.capacityRate_W_K;

simulation = struct( ...
    'time_s', time_s, ...
    'itLoad_W', itLoad_W, ...
    'liquidLoad_W', liquidLoad_W, ...
    'componentTemperature_C', componentTemperature_C, ...
    'returnTemperature_C', returnTemperature_C, ...
    'heatToCoolant_W', heatToCoolant_W, ...
    'storageRate_W', liquidLoad_W - heatToCoolant_W, ...
    'effectiveResistance_K_W', effectiveResistance_K_W, ...
    'timeConstant_s', timeConstant_s);
end

function validateTransientInputs(parameters, time_s, itLoad_W)
requiredFields = [ ...
    "liquidCaptureFraction", "coolantMassFlow_kg_s", ...
    "coolantSpecificHeat_J_kgK", "supplyTemperature_C", ...
    "thermalResistance_K_W", "thermalCapacitance_J_K", ...
    "initialComponentTemperature_C"];
if ~isstruct(parameters) || ~all(isfield(parameters, requiredFields))
    error('DataCenterCooling:MissingTransientParameters', ...
        'parameters must include all required transient-model fields.');
end
if ~isvector(time_s) || numel(time_s) < 2 || any(~isfinite(time_s)) || ...
        any(diff(time_s(:)) <= 0)
    error('DataCenterCooling:InvalidTime', ...
        'time_s must be a finite, strictly increasing vector with at least two points.');
end
if ~isvector(itLoad_W) || numel(itLoad_W) ~= numel(time_s) || ...
        any(~isfinite(itLoad_W)) || any(itLoad_W < 0)
    error('DataCenterCooling:InvalidTransientLoad', ...
        'itLoad_W must be a finite nonnegative vector matching time_s.');
end

steadyInput = struct( ...
    'itLoad_W', 0, ...
    'liquidCaptureFraction', parameters.liquidCaptureFraction, ...
    'coolantMassFlow_kg_s', parameters.coolantMassFlow_kg_s, ...
    'coolantSpecificHeat_J_kgK', parameters.coolantSpecificHeat_J_kgK, ...
    'supplyTemperature_C', parameters.supplyTemperature_C, ...
    'thermalResistance_K_W', parameters.thermalResistance_K_W);
calculateCoolingState(steadyInput);

if ~isscalar(parameters.thermalCapacitance_J_K) || ...
        ~isfinite(parameters.thermalCapacitance_J_K) || ...
        parameters.thermalCapacitance_J_K <= 0
    error('DataCenterCooling:InvalidThermalCapacitance', ...
        'thermalCapacitance_J_K must be a finite, positive scalar in J/K.');
end
if ~isscalar(parameters.initialComponentTemperature_C) || ...
        ~isfinite(parameters.initialComponentTemperature_C)
    error('DataCenterCooling:InvalidInitialTemperature', ...
        'initialComponentTemperature_C must be a finite scalar in degC.');
end
end
