function simulation = simulateComponentTransient(parameters, time_s, itLoad_W)
%SIMULATECOMPONENTTRANSIENT Solve a one-node component-to-liquid model.
%
% Governing equations:
%   C_th*dT_component/dt = Q_liquid - Q_to_coolant
%   Q_to_coolant = (T_component - T_supply)/R_th
%   T_return = T_supply + Q_to_coolant/(m_dot*c_p)
%
% The supplied loop is treated as a fixed-temperature source. This is a
% teaching model that isolates thermal storage and resistance. It does not
% resolve cold-plate geometry, pressure drop, spatial hotspots, or controls.

validateTransientInputs(parameters, time_s, itLoad_W);

time_s = time_s(:);
itLoad_W = itLoad_W(:);
liquidLoad_W = parameters.liquidCaptureFraction .* itLoad_W;

loadAtTime = @(t) interp1(time_s, liquidLoad_W, t, 'previous', 'extrap');
derivative = @(t, temperature_C) (loadAtTime(t) - ...
    (temperature_C - parameters.supplyTemperature_C) ./ ...
    parameters.thermalResistance_K_W) ./ parameters.thermalCapacitance_J_K;

options = odeset('RelTol', 1e-8, 'AbsTol', 1e-10);
[solutionTime_s, componentTemperature_C] = ode45(derivative, time_s, ...
    parameters.initialComponentTemperature_C, options);
componentTemperature_C = componentTemperature_C(:);
liquidLoad_W = interp1(time_s, liquidLoad_W, solutionTime_s, 'previous', 'extrap');
heatToCoolant_W = (componentTemperature_C - parameters.supplyTemperature_C) ./ ...
    parameters.thermalResistance_K_W;
temperatureRate_K_s = (liquidLoad_W - heatToCoolant_W) ./ ...
    parameters.thermalCapacitance_J_K;
returnTemperature_C = parameters.supplyTemperature_C + heatToCoolant_W ./ ...
    (parameters.coolantMassFlow_kg_s * parameters.coolantSpecificHeat_J_kgK);
energyResidual_W = liquidLoad_W - heatToCoolant_W - ...
    parameters.thermalCapacitance_J_K .* temperatureRate_K_s;

simulation = struct( ...
    'time_s', solutionTime_s, ...
    'itLoad_W', itLoad_W, ...
    'liquidLoad_W', liquidLoad_W, ...
    'componentTemperature_C', componentTemperature_C, ...
    'returnTemperature_C', returnTemperature_C, ...
    'heatToCoolant_W', heatToCoolant_W, ...
    'temperatureRate_K_s', temperatureRate_K_s, ...
    'energyResidual_W', energyResidual_W);
end

function validateTransientInputs(parameters, time_s, itLoad_W)
requiredFields = [ ...
    "liquidCaptureFraction", "coolantMassFlow_kg_s", ...
    "coolantSpecificHeat_J_kgK", "supplyTemperature_C", ...
    "thermalResistance_K_W", "thermalCapacitance_J_K", ...
    "initialComponentTemperature_C"];
if ~isstruct(parameters) || ~all(isfield(parameters, requiredFields))
    error('DataCenterCooling:MissingTransientParameters', ...
        'parameters must include all required transient-model fields.');
end
if ~isvector(time_s) || numel(time_s) < 2 || any(~isfinite(time_s)) || ...
        any(diff(time_s(:)) <= 0)
    error('DataCenterCooling:InvalidTime', ...
        'time_s must be a finite, strictly increasing vector with at least two points.');
end
if ~isvector(itLoad_W) || numel(itLoad_W) ~= numel(time_s) || ...
        any(~isfinite(itLoad_W)) || any(itLoad_W < 0)
    error('DataCenterCooling:InvalidTransientLoad', ...
        'itLoad_W must be a finite nonnegative vector matching time_s.');
end

steadyInput = struct( ...
    'itLoad_W', 0, ...
    'liquidCaptureFraction', parameters.liquidCaptureFraction, ...
    'coolantMassFlow_kg_s', parameters.coolantMassFlow_kg_s, ...
    'coolantSpecificHeat_J_kgK', parameters.coolantSpecificHeat_J_kgK, ...
    'supplyTemperature_C', parameters.supplyTemperature_C);
calculateCoolingState(steadyInput);

if ~isscalar(parameters.thermalResistance_K_W) || ...
        ~isfinite(parameters.thermalResistance_K_W) || ...
        parameters.thermalResistance_K_W <= 0
    error('DataCenterCooling:InvalidThermalResistance', ...
        'thermalResistance_K_W must be a finite, positive scalar in K/W.');
end
if ~isscalar(parameters.thermalCapacitance_J_K) || ...
        ~isfinite(parameters.thermalCapacitance_J_K) || ...
        parameters.thermalCapacitance_J_K <= 0
    error('DataCenterCooling:InvalidThermalCapacitance', ...
        'thermalCapacitance_J_K must be a finite, positive scalar in J/K.');
end
if ~isscalar(parameters.initialComponentTemperature_C) || ...
        ~isfinite(parameters.initialComponentTemperature_C)
    error('DataCenterCooling:InvalidInitialTemperature', ...
        'initialComponentTemperature_C must be a finite scalar in degC.');
end
end
